logsBucket: "gs://testing-ci-cd-dataform-saksham/logs"

substitutions:
  _LOCATION: us-central1
  _REPO: testing-ci-cd
  _PROJECT: 	data-exporter-424705

steps:
  # - id: "Dataform Compilation"
  #   name: "node:20"
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       set -euo pipefail
  #       echo ">>> Installing Dataform CLI..."
  #       npm install -g @dataform/cli 
  #       echo ">>> Compiling Dataform project..."
  #       dataform compile --project-dir . 
  #       echo ">>> Compilation finished."

  # - id: "Create Compilation Result Resource"
  #   name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  #   entrypoint: bash
  #   secretEnv: ['DF_CRED']
  #   args:
  #     - -c
  #     - |
  #       set -euo pipefail
  #       echo ">>> Authenticating with GCP..."
  #       echo "$$DF_CRED" > /workspace/.df-credentials.json
  #       gcloud auth activate-service-account --key-file=/workspace/.df-credentials.json --project=${_PROJECT} --quiet
  #       echo ">>> Creating compilation result resource..."
  #       curl -s -X POST \
  #         -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  #         -H "Content-Type: application/json" \
  #         -d '{"releaseConfig":"projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/releaseConfigs/testingrelease"}' \
  #         "https://dataform.googleapis.com/v1beta1/projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/compilationResults" \
  #         | tee /workspace/response.json
  #       tr -d '\r' < /workspace/response.json > /workspace/response_clean.json
  #       echo ">>> Compilation result resource created."

  # - id: "Refresh Dataform Release Configuration and Get Latest Compilation"
  #   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       set -euo pipefail
  #       echo ">>> Refreshing Dataform Release Configuration ..."
  #       apt-get update && apt-get install -y jq 

  #       echo "Using commit SHA: ${COMMIT_SHA}"
  #       echo "Using compilation result: $(jq -r '.name' /workspace/response_clean.json)"

  #       # PATCH request with updateMask
  #       curl -s -X PATCH \
  #         -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  #         -H "Content-Type: application/json" \
  #         -d "{\"releaseCompilationResult\":\"$(jq -r '.name' /workspace/response_clean.json)\",\"gitCommitish\":\"${COMMIT_SHA}\"}" \
  #         "https://dataform.googleapis.com/v1beta1/projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/releaseConfigs/testingrelease?updateMask=releaseCompilationResult,gitCommitish" \
  #         | tee /workspace/release_response.json

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


  - id: "Refresh Dataform Release Configuration with latest commit"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    secretEnv: ['DF_CRED']
    args:
      - '-c'
      - |
        set -euo pipefail
        echo ">>> Authenticating with GCP..."
        echo "$$DF_CRED" > /workspace/.df-credentials.json
        gcloud auth activate-service-account --key-file=/workspace/.df-credentials.json --project=${_PROJECT} --quiet
        echo ">>> Refreshing Dataform Release Configuration ..."
        apt-get update && apt-get install -y jq 
        echo "Using commit SHA: ${COMMIT_SHA}"

        curl -s -X PATCH \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d "{\"gitCommitish\":\"${COMMIT_SHA}\"}" \
          "https://dataform.googleapis.com/v1beta1/projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/releaseConfigs/testingrelease?updateMask=gitCommitish" \

        curl -s -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d '{"releaseConfig":"projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/releaseConfigs/testingrelease"}' \
          "https://dataform.googleapis.com/v1beta1/projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/compilationResults" \
          | tee /workspace/response.json
        tr -d '\r' < /workspace/response.json > /workspace/response_clean.json


        curl -s -X PATCH \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d "{\"releaseCompilationResult\":\"$(jq -r '.name' /workspace/response_clean.json)\",\"gitCommitish\":\"${COMMIT_SHA}\"}" \
          "https://dataform.googleapis.com/v1beta1/projects/${_PROJECT}/locations/${_LOCATION}/repositories/${_REPO}/releaseConfigs/testingrelease?updateMask=releaseCompilationResult,gitCommitish" \
          | tee /workspace/release_response.json




  # - id: "Execute Dataform Unit Tests"
  #   name: "python:3.11"
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       set -euo pipefail
  #       echo ">>> Installing Python dependencies..."
  #       apt-get update && apt-get install -y jq 
  #       pip install --upgrade pip 
  #       pip install dataform-unit-tests google-cloud-bigquery-storage 
  #       pip install --no-cache-dir db-dtypes pandas pyarrow 
  #       echo ">>> Running Dataform unit tests..."
  #       export COMPILATION_RESULT="$(jq -r '.name' /workspace/response_clean.json)"
  #       export GCP_PROJECT_ID=${_PROJECT}
  #       python -m dataform_unit_testing
  #       echo ">>> Unit tests completed."


  # - id: "Create and Merge PR to test"
  #   name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  #   entrypoint: bash
  #   secretEnv: ["DF_GITHUB_TOKEN"]
  #   args:
  #     - -c
  #     - |
  #       set -euo pipefail
  #       echo ">>> Installing GitHub CLI..."
  #       apt-get update -y && apt-get install -y wget git >/dev/null
  #       wget -q https://github.com/cli/cli/releases/download/v2.62.0/gh_2.62.0_linux_amd64.deb
  #       apt-get install -y ./gh_2.62.0_linux_amd64.deb >/dev/null
  #       echo ">>> Authenticating GitHub CLI..."
  #       echo "$$DF_GITHUB_TOKEN" | gh auth login --with-token
  #       echo ">>> Creating PR from dev → test..."
  #       gh pr create \
  #         --repo "Saksham-EVS/GCP-Dataform-Demo" \
  #         --base test \
  #         --head dev \
  #         --title "Promote dev → test (Automated CI)" \
  #         --body "Automated promotion triggered after successful Dataform unit tests." \
  #       | xargs gh pr merge --merge --admin
  #       echo ">>> PR merged successfully!"

availableSecrets:
  secretManager:
    - versionName: projects/388206646321/secrets/DF_CRED/versions/1
      env: 'DF_CRED'
    # - versionName: projects/388206646321/secrets/saksham-git-pat-new/versions/1
    #   env: "DF_GITHUB_TOKEN"
