logsBucket: "gs://testing-ci-cd-dataform-saksham/logs"
steps:

  # 1. (Optional) Print environment metadata for debugging
  # ----------------------------------------------------
  - id: "Debug Build Info"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "Starting Production CD Pipeline..."
        echo "Branch: $BRANCH_NAME"
        echo "Commit: $COMMIT_SHA"

  # 2. Trigger Composer DAG directly from Cloud Build
  # ----------------------------------------------------
  - id: "Trigger Composer DAG via Composer 3 API"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Triggering DAG: dataform_prod_cd on Composer 3"

        curl -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d "{\"dag_run_id\": \"manual_${BRANCH_NAME}_${COMMIT_SHA}_$(date +%s)\"}" \
          "https://3dcb274976a04d0eafb35ad24ce84b79-dot-us-central1.composer.googleusercontent.com/api/v1/dags/dataform_prod_cd/dagRuns"
timeout: "1200s"   # 20 minutes